# Generated by Django 3.1 on 2021-01-03 15:11

from django.db import migrations, models
import users.functions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pro_pic',
            field=models.ImageField(default='lawyers/defaults/img/user_pro_pic_ogair1.jpg', upload_to=users.functions.user_dir, validators=[users.functions.file_size], verbose_name='Profile Picture'),
        ),
    ]
