# Generated by Django 3.1 on 2020-12-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('M', 'Manager'), ('L', 'Lawyer'), ('C', 'Customer')], default='C', max_length=1),
        ),
    ]
