# Generated by Django 3.1 on 2021-01-03 20:34

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(400000), djmoney.models.validators.MaxMoneyValidator({'EUR': 4000, 'USD': 4000})], verbose_name='Consultation Fee'),
        ),
    ]
