# Generated by Django 3.1 on 2020-12-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201226_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1),
        ),
    ]
