# Generated by Django 3.1 on 2020-12-27 16:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201227_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='document',
            field=models.FileField(upload_to=users.models.user_directory_path_lawyer_profile, validators=[users.models.file_size, users.models.content_type_pdf], verbose_name='Official Document'),
        ),
    ]
