# Generated by Django 3.1 on 2020-12-27 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('customer', models.ManyToManyField(related_name='appointment_customers', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ManyToManyField(related_name='appointment_lawyers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
