# Generated by Django 3.1 on 2021-01-03 20:53

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(max_length=500)),
                ('fee_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('BDT', 'Taka'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3)),
                ('fee', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, verbose_name='Consultation Fee')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('cancelled_by', models.CharField(choices=[('', 'None'), ('M', 'Manager'), ('L', 'Lawyer'), ('C', 'Customer')], default='', max_length=1, verbose_name='Cancelled By')),
            ],
        ),
    ]
