# Generated by Django 3.1 on 2020-12-27 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ManyToManyField(related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lawyer',
            field=models.ManyToManyField(related_name='lawyer_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
