# Generated by Django 3.1 on 2021-01-03 20:34

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210103_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, verbose_name='Consultation Fee'),
        ),
    ]
