# Generated by Django 3.1 on 2020-12-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_cancelled_by_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_cancelled_by_lawyer',
            field=models.BooleanField(default=False),
        ),
    ]
