# Generated by Django 3.1 on 2020-12-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201230_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_cancelled_by_manager',
            field=models.BooleanField(default=False),
        ),
    ]
