# Generated by Django 3.1 on 2021-01-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_is_cancelled_by_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(choices=[('', 'None'), ('M', 'Manager'), ('L', 'Lawyer'), ('C', 'Customer')], default='', max_length=1, verbose_name='Cancelled By'),
        ),
    ]
